language: go

go:
  - 1.5

addons:
  artifacts: true
  debug: true

sudo: false

install:
  - go get github.com/moovweb/gokogiri

env:
  global:
    - ARTIFACTS_TARGET_PATHS="$TRAVIS_BRANCH/$GIMME_OS/$GIMME_ARCH"
    - CGO_ENABLED=1

  matrix:
  - GIMME_OS=linux GIMME_ARCH=amd64
  - GIMME_OS=linux GIMME_ARCH=386
  - GIMME_OS=darwin GIMME_ARCH=amd64
  - GIMME_OS=darwin GIMME_ARCH=386
  - GIMME_OS=windows GIMME_ARCH=amd64
  - GIMME_OS=windows GIMME_ARCH=386

script:
  - make test
  - echo $ARTIFACTS_TARGET_PATHS

notifications:
  email: false
