language: go

sudo: false

install:
  - go get github.com/moovweb/gokogiri

env:
  - GIMME_OS=linux GIMME_ARCH=amd64
  - GIMME_OS=darwin GIMME_ARCH=amd64
  - GIMME_OS=windows GIMME_ARCH=amd64

script:
  - make test

notifications:
  email: false
