language: go

addons:
  artifacts: true
  debug: true

sudo: false

install:
  - go get github.com/moovweb/gokogiri

env:
  - GIMME_OS=linux GIMME_ARCH=amd64 CGO_ENABLED=1
  - GIMME_OS=darwin GIMME_ARCH=amd64 CGO_ENABLED=1
  - GIMME_OS=windows GIMME_ARCH=amd64 CGO_ENABLED=1

script:
  - go build -o xp-$GIMME_OS-$GIMME_ARCH -v ./.
  - make test

notifications:
  email: false
