language: go

addons:
  artifacts: true
  # s3_region: "us-west-1" # defaults to "us-east-1"
  debug: true

sudo: false

install:
  - go get github.com/moovweb/gokogiri

env:
  - GIMME_OS=linux GIMME_ARCH=amd64 CGO_ENABLED=1
  - GIMME_OS=darwin GIMME_ARCH=amd64 CGO_ENABLED=1
  - GIMME_OS=windows GIMME_ARCH=amd64 CGO_ENABLED=1

script:
  - make test

notifications:
  email: false
