language: go

go:
  - 1.5

addons:
  artifacts: true

sudo: false

install:
  - go get github.com/moovweb/gokogiri

env:
  matrix:
    - GIMME_OS=linux GIMME_ARCH=amd64
    - GIMME_OS=linux GIMME_ARCH=386
    - GIMME_OS=darwin GIMME_ARCH=amd64
    - GIMME_OS=darwin GIMME_ARCH=386

  global:
    - CGO_ENABLED=1
    - ARTIFACTS_TARGET_PATHS="builds"
    - ARTIFACTS_DEBUG=1

script:
  - go build -o xq-$TRAVIS_BRANCH-$GIMME_OS-$GIMME_ARCH -v ./.
  - make test
  - echo $ARTIFACTS_TARGET_PATHS

notifications:
  email: false
